version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ~/db_data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  php5:
    build: .
    volumes:
      - .:/php5
    ports:
      - 8000:8000
    links:
      - mysql
